[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
smart_contracts = "GLxHTC5L9xNL34hGmpQWnLvi1kANyPJmL4FhdeNvmBQq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/aspirin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
